config/urls.py

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
    path('login/', views.LoginView.as_view(), name="login"),
    path('logout/', views.LogoutView.as_view(), name="logout"),
    path('', include('product_app.urls', namespace='products')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product_app/urls.py
from django.urls import path
from product_app import views

app_name = 'products'

urlpatterns = [
    path('', views.HomePageView.as_view(), name='home' ),
    path('list/', views.ProductListView.as_view(), name="list"),
    path('detail/<int:pk>/', views.ProductDetailView.as_view(), name="detail"),
    path('create/', views.ProductCreateView.as_view(), name="create"),
    path('Update/<int:pk>/', views.ProductUpdateView.as_view(), name="update"),
    path('search/<int:cat>/', views.searchProduct, name="search"),
]

product_app/models.py
import os, random, datetime
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.urls import reverse
from PIL import Image


def photo_path(instance, filename):
    basefilename, file_extension= os.path.splitext(filename)
    date = datetime.datetime.now()
    return f'{instance.prod_code}/{date}-{instance.prod_code}{file_extension}'


PRODUCT_CATEGORY = [
    (0, _('Sofa')),
    (1, _('Sponge Sofa')),
    (2, _('Table')),
    (3, _('Chair')),
    (4, _('Curtain')),
    (5, _('Back Rest')),
    (6, _('Arm Rest')),
    (7, _('Pillow')),
]


class Product(models.Model):
    """
    Manage Product Information
    """
    prod_code = models.CharField(max_length=255, unique=True)
    category = models.IntegerField(choices=PRODUCT_CATEGORY, default=0)
    unit_price = models.PositiveIntegerField(default=0)
    updated_on = models.DateTimeField(auto_now=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(default='default.png', upload_to = photo_path)

    def __str__(self):
        return self.prod_code

    def save(self, *args, **kwargs):
        super(Product, self).save(*args, **kwargs)
        img = Image.open(self.image.path)
        if img.height > 300 or img.width > 400:
            output_size = (300, 400)
            img.thumbnail(output_size)
            img.save(self.image.path)

    def get_absolute_url(self):
        return reverse('products:detail', kwargs={'pk':self.pk})
    
    class Meta:
        ordering = ['category']

product_app/forms.py
from django import forms
from . import models

class ProductForm(forms.ModelForm):
    class Meta:
        model = models.Product
        fields = "__all__"

        widgets ={
            "prod_code": forms.TextInput(attrs={'class':'form-control', 'placeholder':'Uniq Product Code e.g: AA982'}),
            "category": forms.Select(attrs={'class':'form-control'}),
            "unit_price": forms.TextInput(attrs={'class':'form-control'}),
            "image" : forms.FileInput(attrs={'class':'my-2'})
            }

product_app/views.py
from django.shortcuts import render, HttpResponse
from django.utils.translation import gettext as _
from django.views import generic
from . import models, forms

class HomePageView(generic.TemplateView):
    template_name = 'product_app/home.html'


class ProductListView(generic.ListView):
    template_name = 'product_app/product_list.html'
    paginate_by = 3
    model = models.Product

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = models.PRODUCT_CATEGORY
        return context
    

class ProductDetailView(generic.DetailView):
    template_name = 'product_app/product_detail.html'
    model = models.Product


class ProductCreateView(generic.CreateView):
    template_name = 'product_app/product_form.html'
    form_class = forms.ProductForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['state'] = "create"
        return context


class ProductUpdateView(generic.UpdateView):
    template_name = 'product_app/product_form.html'
    model = models.Product
    form_class = forms.ProductForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['state'] = "update"
        return context


def searchProduct(request, cat):
    template = 'product_app/product_list.html'
    products = models.Product.objects.filter(category=cat)


    print(products)

    context = {
        'object_list': products,
        'categories' : models.PRODUCT_CATEGORY,
        'searched': 1
    }
    return render(request, template, context)

product_app/templates/product_app/home.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block main %}
    <div id="carouselIndicators" class="carousel slide my-2" data-ride="carousel">
      <ol class="carousel-indicators">
        <li data-target="#carouselIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselIndicators" data-slide-to="1"></li>
        <li data-target="#carouselIndicators" data-slide-to="2"></li>
      </ol>
      <div class="carousel-inner">
        <div class="carousel-item active">
          <img src="{% static 'media/carousal/crsl-1.jpg' %}" class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item">
          <img src="{% static 'media/carousal/crsl-2.jpg' %}" class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item">
          <img src="{% static 'media/carousal/crsl-3.jpg' %}" class="d-block w-100" alt="...">
        </div>
      </div>
      <a class="carousel-control-prev" href="#carouselIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#carouselIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
    
    <div class="my-3 text-center">
      <p class="text-uppercase display-3 text-warning">{% trans "35 years of experiance" %}</p>
      <hr>
      <p class="text-uppercase h1 text-info">{% trans "Quality over Quantity" %}</p>
      <hr>
      <p class="text-uppercase h1 text-success">{% trans "Customers Trust" %}</p>
      <hr>
      <p class="h4 text-secondary"><span>{% trans "Master" %} </span> : <span>{% trans "Md Kamal Hossain" %}</span></p>
      <p class="h4 text-secondary"><span>{% trans "Mobile" %}</span> : <span>{% trans "0566371754" %}</span></p>
      <hr>
      <p class="h5 text-secondary">{% trans "Address: Al Azizia, Al Madinah Al Manawarah, KSA" %}</p>
    </div>
  <hr>
    <div class="map row my-5">
    <iframe class="col-10 offset-1" src="https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d284.6070104519259!2d39.516024273147906!3d24.46393408159987!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e1!3m2!1sen!2sbd!4v1593028416541!5m2!1sen!2sbd" frameborder="0" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
    </div>
  <hr>
{% endblock main %}

product_app/templates/product_app/product_base.html
{% extends 'base.html' %}

{% block main %}
    <div class="row">
            <div class="prod col-sm-12 col-md-8">
                {% block content %}{% endblock content %}
            </div>
            <div class="sidebar col-sm-12 col-md-4">
                {% block sidebar %} {% endblock sidebar %}
            </div>
    </div>
{% endblock main %}

product_app/templates/product_app/product_detail.html
{% extends './product_base.html' %}
{% load static %}
{% load i18n %}

{% block main %}

<div class="row">
    <div class="col-sm-10 col-md-8 col-lg-4 offset-sm-1 offset-md-2 offset-lg-4">
        <div class="card my-3 border-success detail-card">
            <h3 class="card-header bg-success text-center text-light">{{object.get_category_display}}</h3>
            <img class="detail-img" src="{{object.image.url}}" alt="Card image">
            <hr>
            <div class="card-body bg-secondary my-2">
                <div class="row">
                    <div class="col-6">Product Code:</div>
                    <div class="col-6">{{object.prod_code}}</div>
                </div>
                <hr>
                <div class="row">
                    <div class="col-6">Unit Price:</div>
                    <div class="col-6">{{object.unit_price}}</div>
                </div>
                <hr>
                <div class="row">
                    <div class="col-6">Price Updated:</div>
                    <div class="col-6">{{object.updated_on | date}}</div>
                </div>
            </div>
            <div class="card-footer bg-success text-light text-center ">
                <p> {% trans "Contact Us For Inquary: 0566371754" %}</p>
                {% if requst.user is is_staff %}
                    <a class="btn btn-primary form-control" href="{% url 'products:update' object.id %}">Update</a>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock main %}





product_app/templates/product_app/product_form.html
{% extends './product_base.html' %}
{% load static %}
{% load i18n %}

{% block main %}
<div class="row">
    <div class="col-sm-10 col-md-8 col-lg-4 offset-sm-1 offset-md-2 offset-lg-3 my-5">
        <div class="card rounded">
            <legend class="text-center bg-success text-light py-3 rounded">Product {{state}} Form</legend>
            <form class="p-2" method="post">
            {% csrf_token %}
            {{form}}
            <button class="btn btn-success form-control text-upper" type="submit">{{state}}</button>
        </form>
    </div>
</div>
</div>
{% endblock main %}

product_app/templates/product_app/product_list.html
{% extends './product_base.html' %}
{% load static %}
{% load i18n %}

{% block content %}
<div class="row">
    <div class="col-md-8 col-lg-6 offset-md-2 offset-lg-3">
        {% if object_list %}
        {% for product in object_list %}
        <a class='text-dark cardLink' href="{% url 'products:detail' product.pk %}">
            <div class="card my-5 border-success">
                <p class="card-header bg-success h4 text-light d-flex justify-content-between">
                    <span>{{ product.get_category_display }}</span>
                    <span>{% trans "Product Code" %} - {{ product.prod_code }}</span>
                </p>
                <img class="card-img-top my-2" src="{{ product.image.url }}" alt="Card image cap">
                <div class="card-footer bg-success text-light text-center ">
                    <p> {% trans "Click To view detail" %}</p>
                </div>
            </div>
        </a>
        {% endfor %}
        {% else %}
        <p class="display-1 text-center text-info mt-5">{% trans "No Items Found"%}</p>
        {% endif %}
    </div>
</div>

{% if searched != 1 %}
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
        <a href="?page=1">&laquo; {% trans "first"%}</a>
        <a class="mx-2" href="?page={{ page_obj.previous_page_number }}">{% trans "previous"%}</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
        <a class="mx-2" href="?page={{ page_obj.next_page_number }}">{% trans "next"%}</a>
        <a href="?page={{ page_obj.paginator.num_pages }}">{% trans "last"%} &raquo;</a>
        {% endif %}
    </span>
</div>
{% endif %}
{% endblock content %}


{% block sidebar %}
<div class="col-sm-10 col-md-8 col-lg-6 offset-sm-1 offset-md-2 offset-lg-3 cat_form mt-3 my-sm-3">
    <legend class="text-center"> {% trans "Category" %} </legend>
    <a class="btn btn-primary form-control my-2" href="{% url 'products:list' %}">{% trans "All product"%}</a>
    {% for val,cat in categories %}
    <a href="{% url 'products:search' val %}" class="btn btn-primary form-control my-2" type='submit'>{{cat}}</a>
    {% endfor %}
</div>
{% endblock sidebar %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> {% block title %} {% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/all.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>

{% include 'main-nav.html' %}

<div class="container-fluid mt-1">
    {% block main %}
    {% endblock main %}
</div>


{% include 'footer.html' %}

templates/footer.html
{% load static %}
{% load i18n %}

<footer class=" bg-dark text-center text-light py-5"> 
    <p> Copy Right @SHAHD FOR UPHOLSTERY</p> 
    <p>{% trans "Md Kamal Hossain" %}</p>
    <p>{% trans "Contact: 0566371754" %}</p>
</footer>

<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/popper.js' %}"></script>
<script src="{% static 'js/bootstrap.js' %}"></script>
<script src="{% static 'js/all.js' %}"></script>
</body>
</html>

templates/main-nav.html
{% load i18n %}
{% load static %}

<nav class="navbar navbar-expand-lg navbar-dark bg-primary d-flex justify-content-between ">
  <a class="navbar-brand" href="#"><img src="{% static 'media/logo.png'%}" alt=""></a>
  <P class="name text-light d-lg-none">{% trans "SHAHD FOR UPHOLSTERY" %}</P>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor"
    aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarColor">
    <ul class="navbar-nav d-flex mr-sm-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">{% trans "Home" %} <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'products:list' %}">{% trans "Products" %} <span
            class="sr-only">(current)</span></a>
      </li>
      {% if user.is_authenticated %}
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'products:create' %}">{% trans "Upload" %} <span
            class="sr-only">(current)</span></a>
      </li>
      {% endif %}
      <li class="nav-item">
      </li>
    </ul>
    <P class="name text-light d-md-none d-sm-none d-lg-block mr-auto">{% trans "SHAHD FOR UPHOLSTERY" %}</P>
    <div class="d-lg-flex">
      <div class="mr-3 my-sm-2">
        {% if user.is_authenticated %}
        <a class="btn btn-outline-warning" href="{% url 'logout' %}">  {% trans "Logout" %}</a>
        {% else %}
        <a class="btn btn-outline-success" href="{% url 'login' %}"> {% trans "Login" %}</a>
        {% endif %}
      </div>
      <form class="form-inline" action="{% url 'set_language' %}" method="post">{% csrf_token %}
        <input name="next" type="hidden" value="{{ redirect_to }}">
        <select class="form-control mr-sm-2" name="language">
          {% get_current_language as LANGUAGE_CODE %}
          {% get_available_languages as LANGUAGES %}
          {% get_language_info_list for LANGUAGES as languages %}
          {% for language in languages %}
          <option value="{{ language.code }}" {% if language.code == LANGUAGE_CODE %} selected{% endif %}>
            {{ language.name_local }}
          </option>
          {% endfor %}
        </select>
        <button class="btn btn-outline-success my-2 my-sm-0">{% trans "SELECT" %}</button>
      </form>
    </div>
  </div>
</nav>